$("#datepicker").datepicker({
  firstDay: 1,
  closeText: "Fermer",
  prevText: "Précédent",
  nextText: "Suivant",
  currentText: "Aujourd'hui",
  monthNames: [
    "Janvier",
    "Février",
    "Mars",
    "Avril",
    "Mai",
    "Juin",
    "Juillet",
    "Août",
    "Septembre",
    "Octobre",
    "Novembre",
    "Décembre",
  ],
  //   monthNamesShort: [
  //     "janv.",
  //     "févr.",
  //     "mars",
  //     "avr.",
  //     "mai",
  //     "juin",
  //     "juil.",
  //     "août",
  //     "sept.",
  //     "oct.",
  //     "nov.",
  //     "déc.",
  //   ],
  //   dayNames: [
  //     "dimanche",
  //     "lundi",
  //     "mardi",
  //     "mercredi",
  //     "jeudi",
  //     "vendredi",
  //     "samedi",
  //   ],
  //   dayNamesShort: ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
  dayNamesMin: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
  weekHeader: "Sem.",
  dateFormat: "dd/mm/yy",
  firstDay: 1,
  isRTL: false,
  showMonthAfterYear: false,
  yearSuffix: "",
});

$(document).on("change", "#datepicker", function () {
  console.log($(this).val());
});
